# -*- coding: utf-8 -*-
"""Catálogo Tarea 11 — reportes simples RS-01 … RS-12."""
from __future__ import annotations

REPORTS: list[dict] = [
    {
        "id": "RS-01",
        "name": "Listado de solicitudes pendientes de revisión y aprobación",
        "objetivo": "OT1",
        "para_que": "Ver qué pedidos de clientes todavía no han sido revisados ni aprobados.",
        "quien": "Vendedor, jefe comercial, administrador",
        "columns": [
            "request_id",
            "client_name",
            "client_email",
            "status",
            "payment_status",
            "total",
            "created_at",
        ],
    },
    {
        "id": "RS-02",
        "name": "Listado de pedidos con pago pendiente o a crédito",
        "objetivo": "OT2",
        "para_que": "Ver qué clientes aún no han pagado o compraron a crédito.",
        "quien": "Gerente comercial, administrador, vendedor",
        "columns": [
            "request_id",
            "client_name",
            "payment_status",
            "total",
            "status",
            "created_at",
        ],
    },
    {
        "id": "RS-03",
        "name": "Listado de productos con stock bajo el mínimo",
        "objetivo": "OT3",
        "para_que": "Detectar productos que se están acabando para pedir reposición.",
        "quien": "Jefe de inventario, comprador",
        "columns": ["sku", "product_name", "inventory_quantity", "unit_price", "unit_cost", "vendor_name"],
    },
    {
        "id": "RS-04",
        "name": "Listado de chats de clientes que esperan respuesta",
        "objetivo": "OT6",
        "para_que": "Ver qué clientes escribieron y todavía no recibieron respuesta del personal.",
        "quien": "Vendedor, administrador",
        "columns": ["thread_email", "last_body", "last_at", "message_count", "espera_respuesta"],
    },
    {
        "id": "RS-05",
        "name": "Listado de órdenes de compra abiertas (enviada o parcial)",
        "objetivo": "OT4",
        "para_que": "Ver pedidos a proveedores que todavía no llegan completos a bodega.",
        "quien": "Jefe de compras, comprador",
        "columns": ["po_id", "vendor_name", "status", "created_at", "received_at", "notes"],
    },
    {
        "id": "RS-06",
        "name": "Listado de proveedores activos",
        "objetivo": "OT4",
        "para_que": "Consultar con qué proveedores se puede comprar hoy.",
        "quien": "Jefe de compras, comprador",
        "columns": ["vendor_id", "name", "country", "email", "phone", "active"],
    },
    {
        "id": "RS-07",
        "name": "Listado de pedidos listos que aún no se han enviado",
        "objetivo": "OT5",
        "para_que": "Ver pedidos convertidos en venta que todavía no salieron de bodega.",
        "quien": "Jefe de logística, vendedor",
        "columns": ["request_id", "client_name", "order_id", "total", "created_at"],
    },
    {
        "id": "RS-08",
        "name": "Listado de pedidos enviados que aún no se han entregado",
        "objetivo": "OT5",
        "para_que": "Seguir pedidos en camino hasta que el cliente los reciba.",
        "quien": "Jefe de logística, vendedor",
        "columns": ["request_id", "client_name", "tracking", "shipped_at", "total"],
    },
    {
        "id": "RS-09",
        "name": "Listado de cupones de descuento activos",
        "objetivo": "OT9",
        "para_que": "Ver qué cupones están activos hoy en la tienda.",
        "quien": "Gerente comercial, administrador",
        "columns": ["code", "discount_type", "value", "uses", "max_uses", "active"],
    },
    {
        "id": "RS-10",
        "name": "Listado de usuarios y sus roles",
        "objetivo": "OT8",
        "para_que": "Revisar quién tiene acceso al sistema y con qué rol.",
        "quien": "Administrador",
        "columns": ["name", "email", "role", "active"],
    },
    {
        "id": "RS-11",
        "name": "Listado de productos del catálogo / tienda por categoría",
        "objetivo": "OT7/OT10",
        "para_que": "Ver el catálogo de productos disponibles para vender.",
        "quien": "Vendedor, administrador, analista",
        "columns": ["product_name", "category", "sku", "unit_price", "inventory_quantity", "status"],
    },
    {
        "id": "RS-12",
        "name": "Listado de solicitudes revisadas por vendedor",
        "objetivo": "OT1",
        "para_que": "Ver qué vendedor revisó cada solicitud y cómo quedó el pedido.",
        "quien": "Jefe comercial, administrador",
        "columns": ["request_id", "client_name", "status", "reviewed_by", "created_at", "total"],
    },
]

REPORT_BY_ID = {r["id"]: r for r in REPORTS}
